Add missing dependencies libftdi1-dev libudev-dev
Faced error "thread 'main' panicked at 'Unable to find libudev: `"pkg-config" "--libs" "--cflags" "libudev"` did not exit successfully: exit status: 1" while building with Cross.

Found resolution for issue for Ubuntu Linux install, applied same to docker image: https://github.com/probe-rs/cargo-embed/pull/338